### PR TITLE
Issue 7186 - don't fail on missing .git/info folder

### PR DESCRIPTION
**Pull request by kzlomek**
Signed-off-by: Krystian Zlomek <k.zlomek@eyeo.com>

### CODE REVIEW

**Comment by snoack** [comment]
Please [file a proper issue](https://issues.adblockplus.org/newticket) including information under which circumstances one would run into that error.

**Comment by kzlomek** [comment]
@snoack Sorry about that, I've created ticket and updated pull request and commit title.

**Comment by snoack** [comment]
I'm waiting for feedback by @TriLucas on
https://issues.adblockplus.org/ticket/7186#comment:3.

>

**Comment by TrLucas** [comment]
I left a comment in the issue, IMHO the hassle is not really feasible.

**Pull request closed without merging**
