### PR TITLE
support python3 (mostly) as well as python2

### PR DESCRIPTION
**Pull request by HoverHell**
Single-codebase python2 and python3 support.

The coding style was mostly retained; I recommend doing a pep8ification as a separate task.

Tested only with `build` command.

### CODE REVIEW

**Comment by palant** [comment]
While I certainly appreciate this work, the main reason why we didn't look into Python 3 support so far is M2Crypto - the author tried porting it to Python 3 two years ago but gave up it seems. That module is rather hard to replace...

**Comment by HoverHell** [comment]
> why we didn't look into Python 3 support

You still don't have to seriously look into it. The changes allow using python3 to build some simple packages (e.g. the suspendbackgroundtabs one), without breaking anything (aside from py2.4 if that was ever supported).

**Comment by palant** [comment]
Yes, M2Crypto got irrelevant for Firefox, there is no point in signing packages any more. It's still very important for Chrome and Safari however.

**Comment by snoack** [comment]
I support the attempt migrating to Python 3. But we'd have to replace M2Crypto with something else [pyOpenSSL](https://pyopenssl.readthedocs.org/) looks promising, assuming that it provides all OpenSSL APIs that we need.

Moreover, I'd lend towards supporting Python 3 only here. Otherwise, in particular without automated tests,

**Comment by snoack** [comment]
I support the migration to Python 3.

But we'd have to replace M2Crypto with something else; [pyOpenSSL](https://pyopenssl.readthedocs.org/) looks promising so far.

Moreover, I'd lend towards supporting Python 3 only, here. Otherwise:
* We'd need some abstraction boilerplate
* We'd be limited to the subset of features available in Python 2 and 3
* Testing future changes will be a hassle

**Comment by HoverHell** [comment]
> We'd need some abstraction boilerplate

I.e. a dependency on `six` or a few lines in the file added in this pull request.

> We'd be limited to the subset of features available in Python 2 and 3

Which is generally okay; not many features are specific to py2 or to py3.

> Testing future changes will be a hassle

Thinking a bit more about it, I conclude that it'd still be better to merge these changes, even if the py3 support in these files will be broken in the future due to lack of testing: with these changes it'll be easier to fix it afterwards if needed.

**Comment by snoack** [comment]
M2Crypto has meanwhile been replaced with PyCrypto ([issue 4339](https://issues.adblockplus.org/ticket/4339)). So Python 2-only dependencies are no longer the reason holding back Python 3 support ([issue 5484](https://issues.adblockplus.org/ticket/5484)). However, before performing changes that have an impact on the whole code base, it would be a good idea to first improve test coverage for buildtools ([issue 5383](https://issues.adblockplus.org/ticket/5383) and [issue 5483](https://issues.adblockplus.org/ticket/5483)).

**Comment by snoack** [comment]
We plan to discontinue `buildtools` (in favor of `Gulp.js`). Hence we won't migrate the existing (legacy) code to Python 3, or merge any other non-essential changes for the time being.

**Pull request closed without merging**
