### PR TITLE
Remove misplaced flags from re.sub() calls

### PR DESCRIPTION
**Pull request by jwilk**
`localeTools.py` read:
```python
    if path.endswith('.dtd'):
        data = re.sub(r'<!ENTITY\s+%s\s+"[^"]*">\s*' % key, '', data, re.S)
    else:
        data = re.sub(r'(^|\n)%s=[^\n]*\n' % key, r'\1', data, re.S)
```
But the 4th argument of re.sub() is supposed to be maximum number of substitutions, not flags.
Moreover, the `re.S` flag affects only semantics of the `.` metacharacter, so it wouldn't have any effect on these regexps.

Found using [pydiatra](https://github.com/jwilk/pydiatra).

NB there's a nearly identical bug in `packagerSafari.py`, but I'm too lazy to fix it myself.

### CODE REVIEW

**Comment by palant** [comment]
Jakub, thank you very much, this issue stayed unnoticed for quite some time. Before we can accept any contributions from you, could you sign our [contributor agreement](https://adblockplus.org/eyeo-contributor-license-agreement.pdf) please? A scan or a photo will do, please email it to [me](mailto:trev@adblockplus.org).

**Comment by jwilk** [comment]
That's not going to happen.

**Comment by palant** [comment]
Ok, sorry about that. I'll fix the issue myself then and credit you as the one who found it.

**Comment by palant** [comment]
Created a review here: https://codereview.adblockplus.org/29420565/. Turns out, it is dead code on both occasions so removing it is better than fixing.

**Comment by palant** [comment]
And pushed: https://github.com/adblockplus/buildtools/commit/c8feba7cfd1164527c04230290b9e7450849b7d8

**Pull request closed without merging**
